name: navigation_manager
description: >- 
  Navigation manager for Navigator 2.0 with a convenient declarative way 
  to define application routes.
version: 1.2.0
homepage: https://github.com/nogipx/navigation_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  uri: ^1.0.0
  meta: ^1.3.0
  equatable: ^2.0.3
  universal_io: ^2.0.4

dev_dependencies:
  pedantic: ^1.11.0
