name: navigation_manager
description: >- 
  Navigation manager for Navigator 2.0 with a convenient declarative way 
  to define application routes.
version: 0.0.7
homepage: https://gitlab.com/nogipx/navigation_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  uri: ^0.11.4
  meta: ^1.3.0
  equatable: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
