name: navigation_manager
description: A new Flutter package project.
version: 0.0.1
homepage: https://gitlab.com/nogipx/navigation_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  uri: ^0.11.4
  equatable: ^1.0.0
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
